# @import ./TPL_simulation_base.http

{{
  const config = require("../../config.js").config;
  exports.config = config;
}}

# ---------------------------------
# Variáveis Globais
# ---------------------------------
@ELEVEN_API_KEY = {{ "sk_3db17d18b2ee7f43ef5f6da01166a5d7f48d0d7191fa98c1" ?? config.elevenlabs.api_key }}
@AGENT_ID = {{ "agent_2101k6144df8e9k80spt9h8m63yq" ?? config.elevenlabs.agent_id }}
@baseURL = {{ "https://api.elevenlabs.io" ?? config.elevenlabs.base_url }}

# ---------------------------------
# Configuração do Teste de Simulação
# ---------------------------------

# Diretório de saída para os JSONs de simulação
@JSON_OUT_DIR = ./http-audios/simulation/out

# Componentes para o nome do arquivo (para o helper)
@endpoint = SIMUL
@title = Introdução
@dict = Alias

# Modelo
# Default = gemini-2.5-flash-lite
@llm = gemini-2.5-flash-lite

# Variáveis para a simulação da conversa
@lead =  Natan Lima
@lead_gender = Masculino
@vendor = Felipe Farah
@vendor_gender = Masculino
@enterprise = Prudential
@recommender = Marcio Dantas
@recommender_gender = Masculino
@job = Médico

{{
  exports.partialHistory = [
    {
      "role": "user",
      "message": "Alô, bom dia?",
      "time_in_call_secs": 0
    }
  ];

  exports.dynamicVariables = {
    lead: $context.variables.lead,
    lead_gender: $context.variables.lead_gender,
    vendor: $context.variables.vendor,
    vendor_gender: $context.variables.vendor_gender,
    enterprise: $context.variables.enterprise,
    recommender_name: $context.variables.recommender,
    recommender_gender: $context.variables.recommender_gender,
    job: $context.variables.job,
  };
  exports.maxNewTurns = 6;
}}

###
# @ref simulateResponse